### ISSUE TITLE
parse_date() "ParseError: No numbers were found in input" Python 3.6 and newer

### ISSUE THREAD

**Issue by photodude** [python-babel/babel#1032]
## Overview Description
A traceback happens due to a parsing error in babel parse_date() if the input is string. This is inconsistent with older versions of python 3.5 and older work as expected
## Steps to Reproduce

I'm not sure how to describe the replication of this issue, but please see the following appveyor build
https://ci.appveyor.com/project/j4321/tkcalendar/builds/48195627

## Actual Results
```cmd
Traceback (most recent call last):
  File "C:\projects\tkcalendar\tests\test_calendar.py", line 228, in test_calendar_textvariable 
  year=2015, month=1, day=3, textvariable=var)
  File "C:\projects\tkcalendar\tkcalendar\calendar_.py", line 268, in __init__
    self._sel_date = parse_date(self._textvariable.get(), locale)
  File "C:\PYTHON36\lib\site-packages\babel\dates.py", line 1201, in parse_date
    raise ParseError("No numbers were found in input")
babel.dates.ParseError: No numbers were found in input
```
## Expected Results
date parsed from string input

**Comment by akx** [comment]
Can you share what the input (`self._textvariable.get()`) there had been, and what `locale` was?

**Comment by photodude** [comment]
hi @akx as far as I can tell the input is from nose unit tests in `tkcalendar\tests\test_calendar.py", line 228, in test_calendar_textvariable year=2015, month=1, day=3, textvariable=var)`
https://github.com/j4321/tkcalendar/blob/master/tests/test_calendar.py#L227

Sorry, I struggle running tests like this on local and working through debugging so I'm a bit blind to some things in python which I'm used to doing in C++.

I agree that it's something that changed between babel-2.9.1 and babel-2.11.0
