### ISSUE TITLE
pybabel not running - collections missing (Windows system)

### ISSUE THREAD

**Issue by hjuergs** [python-babel/babel#105]
Hope I'm correct psoting this issue here....
Babel 1.3 is not running 
After installing under windows, python 2.5. I receive an error trying to execute pybabel 
Error:
c:\Trac\Source\Trac-1.0.1>pybabel --version
Traceback (most recent call last):
  File "C:\Python25\Scripts\pybabel-script.py", line 8, in <module>
    load_entry_point('Babel==1.3', 'console_scripts', 'pybabel')()
  File "C:\Python25\lib\site-packages\setuptools-0.6c9-py2.5.egg\pkg_resources.py", line 277, in load_entry_point
  File "C:\Python25\lib\site-packages\setuptools-0.6c9-py2.5.egg\pkg_resources.py", line 2180, in load_entry_point
  File "C:\Python25\lib\site-packages\setuptools-0.6c9-py2.5.egg\pkg_resources.py", line 1913, in load
  File "c:\python25\lib\site-packages\Babel-1.3-py2.5.egg\babel\__init__.py", line 20, in <module>
    from babel.core import UnknownLocaleError, Locale, default_locale, \  File "c:\python25\lib\site-packages\Babel-1.3-py2.5.egg\babel\core.py", line 14, in <module>
    from babel import localedata
  File "c:\python25\lib\site-packages\Babel-1.3-py2.5.egg\babel\localedata.py",
line 17, in <module>
    from collections import MutableMapping
ImportError: cannot import name MutableMapping

**Comment by sils1297** [comment]
Hi,

this bug is very old anf python 2.5 is not supported anymore. I'm therefore closing this, assuming this is an "outdated" issue, if you can reproduce this bug with a supported python version we'd be happy to get a new bug report!

Lasse
