### ISSUE TITLE
Wrong language name for `zh_TW` (Taiwanese)

### ISSUE THREAD

**Issue by SirRob1997** [python-babel/babel#1117]
The language name for Taiwanese (`zh_TW`) seems to be wrongly given as `Chinese` and also the regular locale creation doesnt work as expected:

```python
>>> Locale('zh_TW').get_language_name('en_US')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/poetry/lib/python3.9/site-packages/babel/core.py", line 204, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'zh_TW'
>>> Locale.parse('zh_TW')
Locale('zh', territory='TW', script='Hant')
>>> Locale.parse('zh_TW').get_language_name('en_US')
Chinese
```

As regular "Chinese" I'd classify simplified Han script (Mandarin) while Taiwanese uses traditional Han script.

**Comment by Obscuretone** [comment]
It appears Chinese is correct. [The IANA Language Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) defines zh_TW as follows:

> Type: language
> Subtag: zh
> Description: Chinese
> Added: 2005-10-16
> Scope: macrolanguage

> Type: region
> Subtag: TW
> Description: Taiwan, Province of China
> Added: 2005-10-16

**Comment by StanFromIreland** [comment]
Can this be closed there is nothing to do, it is correct per the IANA standards.

cc @akx
