### ISSUE TITLE
"The babel data files are not available" error on windows platforms

### ISSUE THREAD

**Issue by salimfadhley** [python-babel/babel#113]
I'm getting the following crash when running sphinx on Windows - this is using Babel 1.3. You get the same error regardless of whether easy_install or pip was used to install the project.

It's really easy to reproduce:
1. Install babel (pip or setuptools)
2. Install sphinx
3. Try to build your docs
4. Observe error

FYI, I'm running Python 2.7.3 on Windows Server (32bit)

D:\Apps\Jenkins\workspace\department_retagging_docs\doc>call make.bat html 
Traceback (most recent call last):
  File "D:\Apps\Jenkins\shiningpanda\jobs\3a16c01d\virtualenvs\d41d8cd9\Scripts\sphinx-build-script.py", line 9, in <module>
    load_entry_point('sphinx==1.3b1', 'console_scripts', 'sphinx-build')()
  File "build\bdist.win32\egg\sphinx\__init__.py", line 47, in main
  File "build\bdist.win32\egg\sphinx\__init__.py", line 57, in build_main
  File "build\bdist.win32\egg\sphinx\cmdline.py", line 24, in <module>
  File "build\bdist.win32\egg\sphinx\application.py", line 37, in <module>
  File "build\bdist.win32\egg\sphinx\builders\__init__.py", line 23, in <module>
  File "build\bdist.win32\egg\sphinx\util\i18n.py", line 15, in <module>
  File "build\bdist.win32\egg\babel\messages\__init__.py", line 12, in <module>
  File "build\bdist.win32\egg\babel\messages\catalog.py", line 23, in <module>
  File "build\bdist.win32\egg\babel\dates.py", line 28, in <module>
  File "build\bdist.win32\egg\babel\util.py", line 278, in <module>
  File "build\bdist.win32\egg\babel\localtime\__init__.py", line 21, in <module>
  File "build\bdist.win32\egg\babel\localtime\_win32.py", line 13, in <module>
  File "build\bdist.win32\egg\babel\core.py", line 53, in get_global
  File "build\bdist.win32\egg\babel\core.py", line 25, in _raise_no_data_error
RuntimeError: The babel data files are not available. This usually happens because you are using a source checkout from Babel and you did not build the data files.  Just make sure to run "python setup.py import_cldr" before installing the library.
Archiving artifacts

**Comment by akx** [comment]
This looks like it was fixed by https://github.com/python-babel/babel/commit/a42ac1bbae0b9dbc618e8a83b4d1315732f402f5 .

In addition, #304 would improve this situation further.

Closing this as fixed, nevertheless :)
