### ISSUE TITLE
`locale` parameter cannot be `None`

### ISSUE THREAD

**Issue by injust** [python-babel/babel#1156]
## Overview Description

The type annotations for the `locale` parameter (e.g. in `babel.numbers.format_currency()` suggest that the value can be `None`, but this causes a `TypeError` in `Locale.parse()`.

## Steps to Reproduce

```python
babel.numbers.format_currency(0, "USD", locale=None)
```

## Actual Results

```python
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    babel.numbers.format_currency(0, "USD", locale=None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.13/site-packages/babel/numbers.py", line 777, in format_currency
    locale = Locale.parse(locale)
  File ".venv/lib/python3.13/site-packages/babel/core.py", line 332, in parse
    raise TypeError(f"Unexpected value for identifier: {identifier!r}")
TypeError: Unexpected value for identifier: None
```

## Expected Results

I would expect a value of `None` to use the default value, or `None` should be removed from the type annotations entirely.

**Comment by bestpantusen** [comment]
If possible, I'd like to work on this please.

**Comment by tomasr8** [comment]
> If possible, I'd like to work on this please.

Go for it! Feel free to ask if you need help :)

**Comment by bestpantusen** [comment]
@tomasr8 Please let me know if the PR looks good or missing anything!
