### ISSUE TITLE
format functions fail on infinity

### ISSUE THREAD

**Issue by Changaco** [python-babel/babel#132]
``` python
>>> format_decimal(Decimal('Infinity'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "babel/numbers.py", line 165, in format_decimal
    return pattern.apply(number, locale)
  File "babel/numbers.py", line 563, in apply
    self.frac_prec[1]))
  File "babel/numbers.py", line 380, in bankersround
    a, b = split_number(value)
  File "babel/numbers.py", line 330, in split_number
    for i in range(-exp):
TypeError: bad operand type for unary -: 'str'
```

**Comment by benselme** [comment]
The data is imported from the language files as 'number_symbols', but infinity is not handled.
