### ISSUE TITLE
Figure out why documentation is building flakily

### ISSUE THREAD

**Issue by akx** [python-babel/babel#327]
This was noticed by @wichert on Gitter.

```
docs/api/dates.rst:20: WARNING: autodoc: failed to import function u'format_skeleton' from module u'babel.dates'; the following exception was raised:
Traceback (most recent call last):
  File "autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: format_skeleton

docs/api/languages.rst:12: WARNING: autodoc: failed to import function u'get_official_languages' from module u'babel.languages'; the following exception was raised:
Traceback (most recent call last):
  File "autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named languages
looking for now-outdated files...

docs/api/languages.rst:14: WARNING: autodoc: failed to import function u'get_territory_language_info' from module u'babel.languages'; the following exception was raised:
Traceback (most recent call last):
  File "autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named languages
```

**Comment by sils1297** [comment]
@akx that nondeterministic or dependent on python version or so?

**Comment by akx** [comment]
This seems to have been fixed.
