### ISSUE TITLE
Babel fails to parse a jinja2 template containing a dot expression

### ISSUE THREAD

**Issue by frispete** [python-babel/babel#469]
Hi,

during my very first jinja2 i18n experiments, I stumbled across an ugly issue. Parsing
```
<p>{% trans %}Request performed with <span class="locale-name">{{request.locale_name}}</span> locale.{% endtrans %}</p>
```
results in:
```
extracting messages from pyramid_jinja/templates/fail.jinja2 (silent="False", encoding="utf-8")
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    'update_catalog': babel.update_catalog}
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.4/site-packages/babel/messages/frontend.py", line 454, in run
    for filename, lineno, message, comments, context in extracted:
  File "/usr/lib64/python3.4/site-packages/babel/messages/extract.py", line 156, in extract_from_dir
    dirpath=absname,
  File "/usr/lib64/python3.4/site-packages/babel/messages/extract.py", line 207, in check_and_call_extract_file
    strip_comment_tags=strip_comment_tags
  File "/usr/lib64/python3.4/site-packages/babel/messages/extract.py", line 236, in extract_from_file
    strip_comment_tags))
  File "/usr/lib64/python3.4/site-packages/babel/messages/extract.py", line 317, in extract
    for lineno, funcname, messages, comments in results:
  File "/usr/lib64/python3.4/site-packages/jinja2/ext.py", line 591, in babel_extract
    node = environment.parse(source)
  File "/usr/lib64/python3.4/site-packages/jinja2/environment.py", line 493, in parse
    self.handle_exception(exc_info, source_hint=source)
  File "/usr/lib64/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
  File "/usr/lib64/python3.4/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib64/python3.4/site-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib64/python3.4/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/lib64/python3.4/site-packages/jinja2/parser.py", line 137, in parse_statement
    return ext(self)
  File "/usr/lib64/python3.4/site-packages/jinja2/ext.py", line 264, in parse
    singular_names, singular = self._parse_block(parser, True)
  File "/usr/lib64/python3.4/site-packages/jinja2/ext.py", line 322, in _parse_block
    parser.stream.expect('variable_end')
  File "/usr/lib64/python3.4/site-packages/jinja2/lexer.py", line 386, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '.'
```

There are 3 issues related to this:
 * the misleading 'end of print statement'
 * the absence of a location notification
 * the issue itself

The original problem appeared in a file with 3 dozen translation tags, while babel didn't extract anything. After being inaugurated into the wonders of `silent = False`, the reason was visible, but now spot the issue without a hint which line is the offender...

Sure, the issue can be worked around, since simple expressions work well, just references containing dots seems to be the problem here.

**Comment by akx** [comment]
Hey,

Thanks for the thorough issue report -- always great to see someone dig in. :)

This behavior (aside from the lack of proper exceptions, which is a Jinja issue) is actually documented in [Jinja's documentation on the i18n extension](http://jinja.pocoo.org/docs/2.9/templates/#i18n-in-templates) -- the tl;dr is that you can't use complex expressions within `{% trans %}` blocks. Quoting here for convenience:

> To translate a template expression — say, using template filters, or by just accessing an attribute of an object — you need to bind the expression to a name for use within the translation block:
> ```jinja
> <p>{% trans user=user.username %}Hello {{ user }}!{% endtrans %}</p>
> ```
> If you need to bind more than one expression inside a trans tag, separate the pieces with a comma (,):
> ```jinja
> {% trans book_title=book.title, author=author.name %}
> This is {{ book_title }} by {{ author }}
> {% endtrans %}
> ```
> Inside `trans` tags no statements are allowed, only variable tags are.

**Comment by frispete** [comment]
Hi @akx , thanks -- always great, if someone cares, and even **greater**, if this person has a **clue**.

The pointer is very helpful. Obviously, I missed the link, that is buried in the i18n Extension doc.
FYI, I've searched for [i18n](http://jinja.pocoo.org/docs/2.9/search/?q=i18n), but the second link just pointed to the head of the Template Designer Docs. IOW, the search is missing the hash anchor...

Enough nitpicking, the solution is great. When I saw the transformation of references in the translation sources for the first time, I had an *uncomfortable* feeling, how this could be solved...

I keep this issue open, since IMHO the error message still needs to be improved.
