### ISSUE TITLE
sr_SP Language Not Found

### ISSUE THREAD

**Issue by EndenDragon** [python-babel/babel#555]
When I was compiling translations...
```
Traceback (most recent call last):
  File "/usr/local/bin/pybabel", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/frontend.py", line 908, in main
    return CommandLineInterface().run(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/frontend.py", line 832, in run
    return cmdinst.run()
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/frontend.py", line 182, in run
    self._run_domain(domain)
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/frontend.py", line 221, in _run_domain
    catalog = read_po(infile, locale)
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/pofile.py", line 331, in read_po
    parser.parse(fileobj)
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/pofile.py", line 265, in parse
    self._process_comment(line)
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/pofile.py", line 224, in _process_comment
    self._finish_current_message()
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/pofile.py", line 164, in _finish_current_message
    self._add_message()
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/pofile.py", line 158, in _add_message
    self.catalog[msgid] = message
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/catalog.py", line 596, in __setitem__
    self.mime_headers = _parse_header(message.string).items()
  File "/usr/local/lib/python3.5/dist-packages/babel/messages/catalog.py", line 399, in _set_mime_headers
    self.locale = Locale.parse(value)
  File "/usr/local/lib/python3.5/dist-packages/babel/core.py", line 331, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'sr_SP'
```

It said that sr_SP doesn't exist. Currently crowdin uses that to denote Serbian (Cyrillic) and I would wish to have sr_SP be pointed to that language.

**Comment by akx** [comment]
Hi @EndenDragon!

Yup, looks like `sr_SP` doesn't exist, not even in CLDR 32 (which is not in use yet, but just merged into master).

Anyway, I'll write a PR to fix this and related issues by allowing the catalog code to carry on even if locales are unknown to Babel :)
