### ISSUE TITLE
Are f-strings (PEP 498) supported ?

### ISSUE THREAD

**Issue by JoseKilo** [python-babel/babel#594]
# Overview Description

Not sure if this has been answered before. Are f-strings (PEP 498) supported ?

# Steps to Reproduce

1. I have this input file (`foo.py`)
```python
from gettext import gettext as _


def main():
    foo = "foo"
    print(_(f"Hello {foo}"))


if __name__ == '__main__':
    main()
```

2. I run
```bash
pybabel extract -o locale foo.py
```

# Actual Results

I get this error
```
extracting messages from foo.py
Traceback (most recent call last):
  File "/home/merlin/workspace/babel-test/.venv/bin/pybabel", line 11, in <module>
    sys.exit(main())
  File "/home/merlin/workspace/babel-test/.venv/lib/python3.6/site-packages/babel/messages/frontend.py", line 911, in main
    return CommandLineInterface().run(sys.argv)
  File "/home/merlin/workspace/babel-test/.venv/lib/python3.6/site-packages/babel/messages/frontend.py", line 835, in run
    return cmdinst.run()
  File "/home/merlin/workspace/babel-test/.venv/lib/python3.6/site-packages/babel/messages/frontend.py", line 470, in run
    for filename, lineno, message, comments, context in extracted:
  File "/home/merlin/workspace/babel-test/.venv/lib/python3.6/site-packages/babel/messages/extract.py", line 212, in check_and_call_extract_file
    strip_comment_tags=strip_comment_tags
  File "/home/merlin/workspace/babel-test/.venv/lib/python3.6/site-packages/babel/messages/extract.py", line 241, in extract_from_file
    strip_comment_tags))
  File "/home/merlin/workspace/babel-test/.venv/lib/python3.6/site-packages/babel/messages/extract.py", line 322, in extract
    for lineno, funcname, messages, comments in results:
  File "/home/merlin/workspace/babel-test/.venv/lib/python3.6/site-packages/babel/messages/extract.py", line 484, in extract_python
    value = eval(code, {'__builtins__': {}}, {})
  File "<string>", line 2, in <module>
NameError: name 'foo' is not defined
```

# Expected Results

I understand it should work similarly to

```python
    print(_("Hello {foo}".format(foo=foo)))
```

# Additional Information:

Using `Babel==2.6.0`

**Comment by akx** [comment]
Currently not, unfortunately.

Extracting f-strings would require switching to AST analysis (which was briefly discussed in #415 way back when), so it would take some work.

**Comment by pavlix** [comment]
@akx Extracting yes, that would need it. But would it be possible to do the actual translation in the program? As far as I understand the program uses `_()` function on the final string which reads `f"Hello{foo)"` in the code but the actual value is already `"Hello John"` which *cannot* be translated using `"Hello {foo}"` → `"Hola {foo}"` for example, right? Unless I'm mistaken, PEP 498 completely ignores localization as if you never need to use localized programs with string interpolation.

**Comment by akx** [comment]
Heh, that's true. I didn't even think about it that far.

**Comment by akx** [comment]
So yeah – closing as impossible. Unlike ES6's tagged template literals, f-strings don't have a way to call functions to do the interpolation.
