### ISSUE TITLE
'datetime.date' object has no attribute 'hour' and 'datetime.time' object has no attribute 'day' (guard against invalid access attempts)

### ISSUE THREAD

**Issue by fermulator** [python-babel/babel#664]
hey this is maybe a user error ... what am I doing wrong?

works
``` python
>>> format_date(datetime.utcnow(), 'EEE, d MMM yyyy', locale='en_US')
'Thu, 5 Sep 2019'
```

broken
``` python
>>> format_date(datetime.utcnow(), 'EEE, d MMM yyyy, HH:m:s', locale='en_US')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/babel/dates.py", line 700, in format_date
    return pattern.apply(date, locale)
  File "/usr/local/lib/python3.5/dist-packages/babel/dates.py", line 1232, in apply
    return self % DateTimeFormat(datetime, locale)
  File "/usr/local/lib/python3.5/dist-packages/babel/dates.py", line 1229, in __mod__
    return self.format % other
  File "/usr/local/lib/python3.5/dist-packages/babel/dates.py", line 1274, in __getitem__
    return self.format(self.value.hour, num)
AttributeError: 'datetime.date' object has no attribute 'hour'
```

Seems like babel is lying?
``` python
>>> dt = datetime.utcnow()
>>> dir(dt)
['__add__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__rsub__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', 'astimezone', 'combine', 'ctime', 'date', 'day', 'dst', 'fromordinal', 'fromtimestamp', 'hour', 'isocalendar', 'isoformat', 'isoweekday', 'max', 'microsecond', 'min', 'minute', 'month', 'now', 'replace', 'resolution', 'second', 'strftime', 'strptime', 'time', 'timestamp', 'timetuple', 'timetz', 'today', 'toordinal', 'tzinfo', 'tzname', 'utcfromtimestamp', 'utcnow', 'utcoffset', 'utctimetuple', 'weekday', 'year']
>>> dt.hour
12
```

**Comment by fermulator** [comment]
```
VERSION
    2.5.1
```

**Comment by jun66j5** [comment]
I think `format_datetime()` should be used rather than `format_date()` if you want to use time fields.

```
>>> import babel
>>> babel.__version__
'2.7.0'
>>> from datetime import datetime
>>> from babel.dates import format_date, format_datetime
>>> now = datetime.utcnow()
>>> format_date(now, 'EEE, d MMM yyyy, HH:mm:s', locale='en_US')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python2.7/site-packages/babel/dates.py", line 700, in format_date
    return pattern.apply(date, locale)
  File "/venv/lib/python2.7/site-packages/babel/dates.py", line 1232, in apply
    return self % DateTimeFormat(datetime, locale)
  File "/venv/lib/python2.7/site-packages/babel/dates.py", line 1229, in __mod__
    return self.format % other
  File "/venv/lib/python2.7/site-packages/babel/dates.py", line 1274, in __getitem__
    return self.format(self.value.hour, num)
AttributeError: 'datetime.date' object has no attribute 'hour'
>>> format_datetime(now, 'EEE, d MMM yyyy, HH:mm:s', locale='en_US')
u'Thu, 5 Sep 2019, 13:03:19'
```

**Comment by fermulator** [comment]
aye @jun66j5 , you're right!  I didn't notice this difference :)

probably we should guard against this with a clean error message in the babel code base
1. in `babel.format_date()`, guard against TIME ACCESS attempts
2. in `babel.format_time()`, guard against DATE ACCESS attempts

**Comment by TM2500** [comment]
I could take a look at this, if there is still a need for it.

But I'm still a bit unfamiliar with OS-contribs
