### ISSUE TITLE
Formatting a time delta of 30 minutes in polish does not work anymore

### ISSUE THREAD

**Issue by xoraxax** [python-babel/babel#764]
With 2.5.3:
```
>>> import babel.dates
>>> import datetime
>>> babel.dates.format_timedelta(datetime.timedelta(minutes=30), locale="pl", format='short')
'30 min'
```

With newer versions:
```
>>> import babel.dates
>>> import datetime
>>> babel.dates.format_timedelta(datetime.timedelta(minutes=30), locale="pl", format='short')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/babel/dates.py", line 944, in format_timedelta
    pattern = patterns[plural_form]
  File "/usr/local/lib/python3.7/site-packages/babel/localedata.py", line 218, in __getitem__
    orig = val = self._data[key]
KeyError: 'many'
>>> import pdb; pdb.pm()
[2] > /usr/local/lib/python3.7/site-packages/babel/localedata.py(218)__getitem__()
-> orig = val = self._data[key]
(Pdb++) self._data
{'other': '{0} min', 'per': '{0}/min'}

```

**Comment by akx** [comment]
This was fixed by #827 :)
