### ISSUE TITLE
babel/dates.py: Accesses date.minute attribute (by expecting datetime object)

### ISSUE THREAD

**Issue by jenisys** [python-babel/babel#81]
Potential problem in: babel/dates.py
While using tinkerer 1.3 (which requires Babel (1.3)), I stumbled over the following problem. After looking at the code, I believe that the problem is in Babel, not in tinkerer.
Tinkerer uses "format_date()" which expects a "datatime.date". Somehow this expectation is violated within the "babel.dates" module that afterwards expects a "datetime" object and runs into the missing attribute problem,.

TRACEBACK DATA:

```
# Sphinx version: 1.2.1
# Python version: 2.7.5
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
Traceback (most recent call last):
…
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tinkerer/ext/metadata.py", line 112, in get_metadata
    metadata.formatted_date = format_ui_date(metadata.date)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/babel/dates.py", line 568, in format_date
    return pattern.apply(date, locale)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/babel/dates.py", line 891, in apply
    return self % DateTimeFormat(datetime, locale)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/babel/dates.py", line 888, in __mod__
    return self.format % other
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/babel/dates.py", line 941, in __getitem__
    return self.format(self.value.minute, num)
AttributeError: 'datetime.date' object has no attribute 'minute'
```

**Comment by etanol** [comment]
This still happens when you try to use the minute symbol in the format parametr of `format_date`.  Same happens when trying to use the year symbol in te format parameter of `format_time`.

I think the appropriate solution here is to emulate the Python's standard `strftime` behaviour:

```python
>>> from datetime import datetime, date
>>> today = date.today()
>>> today.strftime("%M")
00
>>> now = datetime.now().time()
>>> now.strftime("%Y")
1900
```

**Comment by etanol** [comment]
On a closer look, this [seems to be the expected behaviour](https://github.com/python-babel/babel/blob/master/tests/test_dates.py#L228).
