### ISSUE TITLE
Crash with bogus locale identifier

### ISSUE THREAD

**Issue by MarcelloPerathoner** [python-babel/babel#87]
I know it is bogus, but that's what you get in the wild.

```
from babel.core import Locale

Locale.parse ('en_UK')
```

```
Traceback (most recent call last):
  File "bug.py", line 3, in <module>
    Locale.parse ('en_UK')
  File "/usr/local/lib/python3.3/dist-packages/babel/core.py", line 297, in parse
    new_id = get_locale_identifier(parts)
  File "/usr/local/lib/python3.3/dist-packages/babel/core.py", line 941, in get_locale_identifier
    return sep.join(filter(None, (lang, script, territory, variant)))
TypeError: sequence item 1: expected str instance, list found
```

python 3.3.5 babel 1.3

**Comment by benselme** [comment]
Works as expected in master.
